services:
  db:
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my-deep-research
    ports:
      - '5433:5432'
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - my-postgres:/var/lib/postgresql/data

volumes:
  my-postgres: 